config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get '/markets', to: 'markets#index'
  get '/markets/:id', to: 'markets#show'
  get "/vendors/:id", to: "vendors#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController

    def index
      @facade = MarketsFacade.new
    end
  
    def show
      @facade = MarketsFacade.new(params[:id])
    end
end
  

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
    def show
      @facade = VendorsFacade.new(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<h1>Markets</h1>

<% @facade.markets.each do |market| %>
<li>
    <%= market.name %> - <%= market.city %>, <%= market.state %>
    <%= button_to 'See more', "/markets/#{market.id}", method: :get %>
</li>
<% end %>

app/views/markets/show.html.erb
<h1><%= @facade.market.name %></h1>

<p>Address: <%= @facade.market.address %></p>
<p>City: <%= @facade.market.city %></p>
<p>State: <%= @facade.market.state %></p>

<h2>Vendors at this Market:</h2>

<div class="vendors">
  <% @facade.market_vendors.each do |vendor| %>
    <div class="vendor">
      <%= link_to vendor.name, "/vendors/#{vendor.id}" %>
    </div>
  <% end %>
</div>
<%= link_to 'Back to Markets', markets_path %> 

app/views/vendors/show.html.erb
<h1><%= @facade.vendor.name %></h1>

<p>Name: <%= @facade.vendor.contact_name %></p>
<p>Phone: <%= @facade.vendor.contact_phone %></p>
<p>Accepts Credit: <%= @facade.vendor.credit_accepted ? 'Yes' : 'No' %></p>
<p>Description: <%= @facade.vendor.description %></p>